FROM docker.io/ubuntu:jammy-20221020

RUN apt-get update \
    && apt-get --quiet --assume-yes --no-install-recommends install \
        locales sudo tzdata apt-transport-https ca-certificates \
    && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
    && echo "en_US.UTF-8 UTF-8"  >> /etc/locale.gen \
    && echo "LANG=en_US.UTF-8"    > /etc/locale.conf \
    && locale-gen en_US.UTF-8 \
    && update-ca-certificates \    
    && apt-get --quiet --assume-yes dist-upgrade \
    && apt-get --quiet --assume-yes --no-install-recommends install \
        automake autoconf g++-12 gcc-12 git make gawk python3 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CC=gcc-12 CXX=g++-12

# TODO: update below URL and branch once merged into uwplse/herbgrind
RUN git clone --branch add-reproducible-container https://github.com/bjodah/herbgrind /opt/herbgrind \
    && cd /opt/herbgrind \
    && make valgrind/README   # this will clone valgrind

RUN cd /opt/herbgrind \
    && git pull \
    && make all

RUN cd /opt/herbgrind \
    && make test
